<?php

/**
 * This is the model base class for the table "UPIPosition".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UPIPosition".
 *
 * Columns in table "UPIPosition" available as properties of the model,
 * followed by relations of table "UPIPosition" available as properties of the model.
 *
 * @property integer $id
 * @property integer $upi
 * @property string $editiontime
 * @property double $latitude
 * @property double $longitude
 *
 * @property UPI $upi0
 */
abstract class BaseUPIPosition extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'UPIPosition';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UPIPosition|UPIPositions', $n);
	}

	public static function representingColumn() {
		return 'editiontime';
	}

	public function rules() {
		return array(
			array('id, upi, editiontime, latitude, longitude', 'required'),
			array('id, upi', 'numerical', 'integerOnly'=>true),
			array('latitude, longitude', 'numerical'),
			array('id, upi, editiontime, latitude, longitude', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'upi0' => array(self::BELONGS_TO, 'UPI', 'upi'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'upi' => null,
			'editiontime' => Yii::t('app', 'Editiontime'),
			'latitude' => Yii::t('app', 'Latitude'),
			'longitude' => Yii::t('app', 'Longitude'),
			'upi0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('upi', $this->upi);
		$criteria->compare('editiontime', $this->editiontime, true);
		$criteria->compare('latitude', $this->latitude);
		$criteria->compare('longitude', $this->longitude);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}