<?php

/**
 * This is the model base class for the table "OnlineUser".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OnlineUser".
 *
 * Columns in table "OnlineUser" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user
 * @property string $user_name
 * @property double $latitude
 * @property double $longitude
 * @property string $time
 * @property string $content
 * @property integer $composite
 * @property string $composite_name
 * @property integer $base
 * @property string $base_name
 * @property integer $upi
 * @property integer $upi_type
 *
 */
abstract class BaseOnlineUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'OnlineUser';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OnlineUser|OnlineUsers', $n);
	}

	public static function representingColumn() {
		return 'user_name';
	}

	public function rules() {
		return array(
			array('user, user_name, latitude, longitude, time', 'required'),
			array('user, composite, base, upi, upi_type', 'numerical', 'integerOnly'=>true),
			array('latitude, longitude', 'numerical'),
			array('user_name, composite_name, base_name', 'length', 'max'=>500),
			array('content', 'safe'),
			array('content, composite, composite_name, base, base_name, upi, upi_type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user, user_name, latitude, longitude, time, content, composite, composite_name, base, base_name, upi, upi_type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user' => Yii::t('app', 'User'),
			'user_name' => Yii::t('app', 'User Name'),
			'latitude' => Yii::t('app', 'Latitude'),
			'longitude' => Yii::t('app', 'Longitude'),
			'time' => Yii::t('app', 'Time'),
			'content' => Yii::t('app', 'Content'),
			'composite' => Yii::t('app', 'Composite'),
			'composite_name' => Yii::t('app', 'Composite Name'),
			'base' => Yii::t('app', 'Base'),
			'base_name' => Yii::t('app', 'Base Name'),
			'upi' => Yii::t('app', 'Upi'),
			'upi_type' => Yii::t('app', 'Upi Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user', $this->user);
		$criteria->compare('user_name', $this->user_name, true);
		$criteria->compare('latitude', $this->latitude);
		$criteria->compare('longitude', $this->longitude);
		$criteria->compare('time', $this->time, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('composite', $this->composite);
		$criteria->compare('composite_name', $this->composite_name, true);
		$criteria->compare('base', $this->base);
		$criteria->compare('base_name', $this->base_name, true);
		$criteria->compare('upi', $this->upi);
		$criteria->compare('upi_type', $this->upi_type);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}