<?php

/**
 * This is the model base class for the table "VComBase".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VComBase".
 *
 * Columns in table "VComBase" available as properties of the model,
 * followed by relations of table "VComBase" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $vcomcomposite
 * @property integer $virtualspace
 *
 * @property UPIAggregationRuleStart[] $uPIAggregationRuleStarts
 * @property VComComposite $vcomcomposite0
 * @property VirtualSpace $virtualspace0
 * @property VComUPIPublication[] $vComUPIPublications
 */
abstract class BaseVComBase extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'VComBase';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VComBase|VComBases', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('id, name, description, vcomcomposite, virtualspace', 'required'),
			array('id, vcomcomposite, virtualspace', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('id, name, description, vcomcomposite, virtualspace', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'uPIAggregationRuleStarts' => array(self::HAS_MANY, 'UPIAggregationRuleStart', 'vcombase'),
			'vcomcomposite0' => array(self::BELONGS_TO, 'VComComposite', 'vcomcomposite'),
			'virtualspace0' => array(self::BELONGS_TO, 'VirtualSpace', 'virtualspace'),
			'vComUPIPublications' => array(self::HAS_MANY, 'VComUPIPublication', 'vcombase'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'vcomcomposite' => null,
			'virtualspace' => null,
			'uPIAggregationRuleStarts' => null,
			'vcomcomposite0' => null,
			'virtualspace0' => null,
			'vComUPIPublications' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('vcomcomposite', $this->vcomcomposite);
		$criteria->compare('virtualspace', $this->virtualspace);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}