<?php

/**
 * This is the model base class for the table "VComUPIPublication".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VComUPIPublication".
 *
 * Columns in table "VComUPIPublication" available as properties of the model,
 * followed by relations of table "VComUPIPublication" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user
 * @property integer $vcombase
 * @property integer $upi
 * @property integer $upiaggregationrulestart
 * @property integer $upiaggregationruleresponseof
 * @property double $latitude
 * @property double $longitude
 *
 * @property User $user0
 * @property VComBase $vcombase0
 * @property UPIAggregationRuleStart $upiaggregationrulestart0
 * @property UPIAggregationRuleResponseOf $upiaggregationruleresponseof0
 * @property UPI $upi0
 */
abstract class BaseVComUPIPublication extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'VComUPIPublication';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VComUPIPublication|VComUPIPublications', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user, vcombase, upi, latitude, longitude', 'required'),
			array('user, vcombase, upi, upiaggregationrulestart, upiaggregationruleresponseof', 'numerical', 'integerOnly'=>true),
			array('latitude, longitude', 'numerical'),
			array('upiaggregationrulestart, upiaggregationruleresponseof', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user, vcombase, upi, upiaggregationrulestart, upiaggregationruleresponseof, latitude, longitude', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user0' => array(self::BELONGS_TO, 'User', 'user'),
			'vcombase0' => array(self::BELONGS_TO, 'VComBase', 'vcombase'),
			'upiaggregationrulestart0' => array(self::BELONGS_TO, 'UPIAggregationRuleStart', 'upiaggregationrulestart'),
			'upiaggregationruleresponseof0' => array(self::BELONGS_TO, 'UPIAggregationRuleResponseOf', 'upiaggregationruleresponseof'),
			'upi0' => array(self::BELONGS_TO, 'UPI', 'upi'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user' => null,
			'vcombase' => null,
			'upi' => null,
			'upiaggregationrulestart' => null,
			'upiaggregationruleresponseof' => null,
			'latitude' => Yii::t('app', 'Latitude'),
			'longitude' => Yii::t('app', 'Longitude'),
			'user0' => null,
			'vcombase0' => null,
			'upiaggregationrulestart0' => null,
			'upiaggregationruleresponseof0' => null,
			'upi0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user', $this->user);
		$criteria->compare('vcombase', $this->vcombase);
		$criteria->compare('upi', $this->upi);
		$criteria->compare('upiaggregationrulestart', $this->upiaggregationrulestart);
		$criteria->compare('upiaggregationruleresponseof', $this->upiaggregationruleresponseof);
		$criteria->compare('latitude', $this->latitude);
		$criteria->compare('longitude', $this->longitude);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}