<?php

/**
 * This is the model base class for the table "UPIAggregationRuleStart".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UPIAggregationRuleStart".
 *
 * Columns in table "UPIAggregationRuleStart" available as properties of the model,
 * followed by relations of table "UPIAggregationRuleStart" available as properties of the model.
 *
 * @property integer $id
 * @property integer $vcombase
 * @property integer $upitype
 * @property string $name
 * @property string $description
 * @property integer $requirePositionToCreate
 * @property integer $requirePositionToView
 * @property integer $republisAllowed
 * @property integer $isSingleton
 * @property integer $visibleDistance
 *
 * @property UPIAggregationRuleResponseOf[] $uPIAggregationRuleResponseOfs
 * @property VComBase $vcombase0
 * @property UPIType $upitype0
 * @property VComUPIAggregationRuleStart[] $vComUPIAggregationRuleStarts
 * @property VComUPIPublication[] $vComUPIPublications
 */
abstract class BaseUPIAggregationRuleStart extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'UPIAggregationRuleStart';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UPIAggregationRuleStart|UPIAggregationRuleStarts', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('vcombase, upitype, name', 'required'),
			array('vcombase, upitype, requirePositionToCreate, requirePositionToView, republisAllowed, isSingleton, visibleDistance', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('description', 'safe'),
			array('description, requirePositionToCreate, requirePositionToView, republisAllowed, isSingleton, visibleDistance', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, vcombase, upitype, name, description, requirePositionToCreate, requirePositionToView, republisAllowed, isSingleton, visibleDistance', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'uPIAggregationRuleResponseOfs' => array(self::HAS_MANY, 'UPIAggregationRuleResponseOf', 'upiaggregationrulestart'),
			'vcombase0' => array(self::BELONGS_TO, 'VComBase', 'vcombase'),
			'upitype0' => array(self::BELONGS_TO, 'UPIType', 'upitype'),
			'vComUPIAggregationRuleStarts' => array(self::HAS_MANY, 'VComUPIAggregationRuleStart', 'upiaggregationrulestart'),
			'vComUPIPublications' => array(self::HAS_MANY, 'VComUPIPublication', 'upiaggregationrulestart'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'vcombase' => null,
			'upitype' => null,
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'requirePositionToCreate' => Yii::t('app', 'Require Position To Create'),
			'requirePositionToView' => Yii::t('app', 'Require Position To View'),
			'republisAllowed' => Yii::t('app', 'Republis Allowed'),
			'isSingleton' => Yii::t('app', 'Is Singleton'),
			'visibleDistance' => Yii::t('app', 'Visible Distance'),
			'uPIAggregationRuleResponseOfs' => null,
			'vcombase0' => null,
			'upitype0' => null,
			'vComUPIAggregationRuleStarts' => null,
			'vComUPIPublications' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('vcombase', $this->vcombase);
		$criteria->compare('upitype', $this->upitype);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('requirePositionToCreate', $this->requirePositionToCreate);
		$criteria->compare('requirePositionToView', $this->requirePositionToView);
		$criteria->compare('republisAllowed', $this->republisAllowed);
		$criteria->compare('isSingleton', $this->isSingleton);
		$criteria->compare('visibleDistance', $this->visibleDistance);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}